### ISSUE TITLE
MemberId와 Password를 한번더 감싼 이유가 뭔가요?

### ISSUE THREAD

**Issue by hankk20** [doremi-study/market-doremi#3]
#2 

클래스도 더 만들어야고 옮겨담을때도 바로 담지도 못하고 꺼내서 써야되서
코딩량이 조금 늘어나서 별론거 같은데 왜 이렇게 했어요?

**라고 누군가 투덜 대면서 질문을 한다면?**

**Comment by sYrongK** [comment]
객체로 감싸서 객체 관련된 기능들 담아두고 응집도를 높이려는...주저리주저리..
패스워드 같은 경우는 안에 유효성 체크 메서드 넣어서 사용한다든지 해보려고요 (feat. 쭈 tdd강의)

**Comment by hankk20** [comment]
네 맞아요

예를 들어 문의 게시판에는 작성자 아이디 전부 보여주고
상품평 게시판에는 작성자 아이디 앞 몇글자만 보여주고
이후는 마스킹처리해서 보여줘야 된다고 업무요건이 오면
MemberId 객체에 포멧팅 기능이 들어가는것도 좋은 방법이죠
